# swig -python example.i
# gcc -c -fPIC example.c example_wrap.c -I/usr/include/python2.6 -I/usr/lib/python2.6
# ld -shared example.o example_wrap.o -o _example.so

# >>> import example
# >>> example.fact(5)
# 120
# >>> example.my_mod(7,3)
# 1
# >>> example.get_time()
# 'Sun Feb 11 23:01:07 1996'
# >>>